apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  labels:
    component: guacamole
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: guacamole
    spec:
      initContainers:
        - name: initdb
          image: docker.io/postgres:9
          volumeMounts:
            - name: guacamole-initdb
              mountPath: /initdb
          env:
            - name: POSTGRES_HOSTNAME
              value: postgres
          envFrom:
            - secretRef:
                name: guacamole-secret
            - secretRef:
                name: postgres-secret
            - configMapRef:
                name: postgres-config
          command:
            - bash
            - /initdb/initdb.sh
      containers:
        - name: guacamole
          image: docker.io/guacamole/guacamole:1.4.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POSTGRES_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: POSTGRES_DB
            - name: POSTGRES_HOSTNAME
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: GUACD_HOSTNAME
              value: guacd
            - name: HOME
              value: /config
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: guacamole-data
              mountPath: /config
      volumes:
        - name: guacamole-data
          emptyDir: {}
        - name: guacamole-initdb
          configMap:
            name: guacamole-initdb
