apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  labels:
    component: guacd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: guacd
    spec:
      containers:
        - name: guacd
          image: docker.io/guacamole/guacd:1.4.0
          ports:
            - containerPort: 4822
              name: guacd
