apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  labels:
    component: oauth2-proxy
spec:
  template:
    metadata:
      labels:
        component: oauth2-proxy
    spec:
      containers:
        - name: oauth2-proxy
          image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: oauth2-config
            - secretRef:
                name: oauth2-secret
