apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    component: postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: postgres
    spec:
      containers:
        - name: postgres
          image: docker.io/postgres:9
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgres-data
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data
