apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shaw-virtual-desktop
commonLabels:
  app: shaw-virtual-desktop
resources:
- namespace.yaml
- deployments/postgres.yaml
- volumes/postgres-data.yaml
- services/postgres.yaml
- services/guacamole.yaml
- deployments/guacamole.yaml
- routes/guacamole.yaml

secretGenerator:
- envs:
  - secrets/postgres.env
  name: postgres-secret
- envs:
  - secrets/guacamole.env
  name: guacamole-secret

configMapGenerator:
- envs:
  - configs/postgres.env
  name: postgres-config
- files:
  - configs/initdb.sh
  - configs/initdb.sql
  name: guacamole-initdb
