apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: shaw-virtual-desktop
commonLabels:
  app: shaw-virtual-desktop
resources:
- namespace.yaml
- deployments/postgres.yaml
- volumes/postgres-data.yaml
- services/postgres.yaml
- services/guacamole.yaml
- deployments/guacamole.yaml
- routes/shaw-virtual-desktop.yaml
- deployments/redis.yaml
- services/oauth2-proxy.yaml
- services/redis.yaml
- volumes/redis-data.yaml
- deployments/guacd.yaml
- services/guacd.yaml

secretGenerator:
- envs:
  - secrets/postgres.env
  name: postgres-secret
- envs:
  - secrets/guacamole.env
  name: guacamole-secret

configMapGenerator:
- envs:
    - configs/guacamole.env
  name: guacamole-config
- envs:
  - configs/postgres.env
  name: postgres-config
- files:
  - configs/initdb.sh
  - configs/initdb.sql
  name: guacamole-initdb
- files:
  - default.conf=configs/nginx-default.conf
  name: nginx-config
