apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: shaw-virtual-desktop-api
  annotations:
    haproxy.router.openshift.io/rewrite-target: /guacamole/api
spec:
  host: shaw-virtual-desktop.apps.ocp-staging.massopen.cloud
  path: /api
  port:
    targetPort: http
  to:
    kind: Service
    name: guacamole
  tls:
    termination: edge
